cloudwego/volo

volo-build/src/grpc_backend.rs
fix the annoying clippy warning message
just ignore it or get a better way to code
=> fix(grpc): codegen clippy warning

volo-grpc/src/lib.rs
=> make message mod public

volo-grpc/Cargo.toml, volo-grpc/src/client/callopt.rs, volo-grpc/src/client/mod.rs, volo-grpc/src/metadata/mod.rs, volo-grpc/src/server/mod.rs, volo-grpc/src/status.rs, volo-grpc/src/transport/client.rs
Support for passing information between client and server by using [Metainfo](https://github.com/cloudwego/metainfo)
=> feat: grpc support metainfo

volo/src/net/dial.rs
=> fix: connect timeout

volo/src/discovery/mod.rs, volo/src/loadbalance/random.rs
=> feat: assert code adjust

volo-grpc/src/status.rs
feat: volo-grpc status code adjust optimize for current type use Self keywords.
=> feat: volo-grpc status code adjust optimize

volo-grpc/src/request.rs, volo-grpc/src/response.rs
code adjust for Response use Self keywords
=> feat: code adjust for Response use Self keywords

volo-build/src/config_builder.rs
fix: includes path for git source
=> fix: includes path for git source

volo-cli/src/init.rs
fix: default namespace for thrift
use filename as default namespcae
=> fix: default namespace for thrift

Cargo.lock, volo-thrift/src/client/mod.rs, volo-thrift/src/codec/framed.rs, volo-thrift/src/codec/mod.rs, volo-thrift/src/error.rs, volo-thrift/src/lib.rs, volo-thrift/src/message.rs, volo-thrift/src/message_wrapper.rs, volo-thrift/src/server.rs, volo-thrift/src/transport/pingpong/client.rs, volo-thrift/src/transport/pingpong/server.rs, volo-thrift/src/transport/pingpong/thrift_transport.rs
=> remove triat `Size`

volo-build/src/thrift_backend.rs
=> fix: remove codegen of `Size`

volo-grpc/src/client/mod.rs, volo-grpc/src/layer/loadbalance/mod.rs, volo-thrift/src/client/mod.rs, volo/src/loadbalance/mod.rs
fix: remove unnecessary generic type of MkLbLayer
=> fix: remove unnecessary generic type of MkLbLayer

Cargo.lock, volo-thrift/src/error.rs
=> fix: write_field_begin args

volo-grpc/README.md
Typo in `volo-grpc` readme
Fixed typo
=> Update README.md (simple typo fix)

rust-toolchain.toml, volo-cli/src/templates/grpc/rust-toolchain_toml, volo-cli/src/templates/grpc/src/bin/server_rs, volo-cli/src/templates/grpc/src/lib_rs, volo-cli/src/templates/grpc/volo-gen/src/lib_rs, volo-cli/src/templates/thrift/rust-toolchain_toml, volo-cli/src/templates/thrift/src/bin/server_rs, volo-cli/src/templates/thrift/src/lib_rs, volo-cli/src/templates/thrift/volo-gen/src/lib_rs, volo-grpc/src/lib.rs, volo-thrift/src/lib.rs, volo/src/lib.rs
=> remove gat feature

volo-thrift/src/client/mod.rs, volo-thrift/src/server.rs, volo-thrift/src/transport/multiplex/client.rs, volo-thrift/src/transport/multiplex/server.rs, volo-thrift/src/transport/multiplex/thrift_transport.rs
=> fix: dep in multiplex

Cargo.lock, volo-build/Cargo.toml, volo-cli/Cargo.toml, volo-grpc/Cargo.toml, volo-thrift/Cargo.toml, volo/Cargo.toml
=> release volo 0.2

Cargo.lock, volo-build/Cargo.toml, volo-cli/Cargo.toml, volo-thrift/Cargo.toml
=> use pilota git source

volo-thrift/src/server.rs, volo-thrift/src/transport/pool/make_transport.rs, volo-thrift/src/transport/pool/mod.rs
=> optimize code

volo-build/src/thrift_backend.rs
optimize: volo codegen for thrift
=> optimize: volo codegen for thrift

Cargo.lock, examples/src/hello/thrift_client.rs, volo-build/src/thrift_backend.rs
Corresponding to https://github.com/cloudwego/pilota/pull/47, https://github.com/cloudwego/pilota/pull/48
=> feat(thrift): support client Arc request

Cargo.lock, examples/src/hello/thrift_client.rs, volo-grpc/src/body.rs, volo-grpc/src/codec/encode.rs, volo-grpc/src/status.rs
fix https://github.com/cloudwego/volo/issues/83
=> fix(grpc): return trailers-only when error occured

volo-grpc/src/client/meta.rs, volo-grpc/src/client/mod.rs, volo-grpc/src/server/meta.rs, volo-grpc/src/server/mod.rs, volo-grpc/src/transport/client.rs
=> chore(grpc): move metainfo logic to metaservice

Cargo.lock, Cargo.toml, examples/src/hello/thrift_client.rs, volo-build/src/config_builder.rs, volo-build/src/grpc_backend.rs, volo-build/src/thrift_backend.rs, volo-grpc/src/client/callopt.rs, volo-grpc/src/client/meta.rs, volo-grpc/src/client/mod.rs, volo-grpc/src/layer/cross_origin.rs, volo-grpc/src/layer/grpc_timeout.rs, volo-grpc/src/layer/loadbalance/mod.rs, volo-grpc/src/layer/user_agent.rs, volo-grpc/src/server/meta.rs, volo-grpc/src/server/mod.rs, volo-grpc/src/transport/client.rs, volo-thrift/src/client/callopt.rs, volo-thrift/src/client/layer/timeout.rs, volo-thrift/src/client/mod.rs, volo-thrift/src/context.rs, volo-thrift/src/server.rs, volo-thrift/src/transport/multiplex/client.rs, volo-thrift/src/transport/multiplex/server.rs, volo-thrift/src/transport/pingpong/client.rs, volo-thrift/src/transport/pingpong/server.rs, volo-thrift/src/transport/pool/make_transport.rs, volo-thrift/src/transport/pool/mod.rs, volo/src/client.rs, volo/src/lib.rs, volo/src/loadbalance/layer.rs
feat: migrate to motore 0.3 & new callopt
=> feat: migrate to motore 0.3 & new callopt

Cargo.lock, Cargo.toml, volo-build/src/thrift_backend.rs
=> fix: unmatched method

Cargo.lock, volo-build/src/thrift_backend.rs, volo-thrift/src/transport/multiplex/client.rs
=> fix: trait bound

examples/src/hello/thrift_client.rs, volo-build/src/thrift_backend.rs, volo-thrift/src/client/mod.rs, volo/src/client.rs
fix: lifetime is not general enough
=> fix: lifetime is not general enough

volo-build/src/grpc_backend.rs, volo-build/src/thrift_backend.rs, volo-build/src/util.rs, volo-grpc/src/client/callopt.rs, volo-grpc/src/client/mod.rs, volo-grpc/src/lib.rs, volo-thrift/src/client/mod.rs
=> callopt for grpc

volo-build/src/grpc_backend.rs
=> fix(grpc): MkGenericClient in codegen

volo-build/src/grpc_backend.rs, volo-grpc/src/client/mod.rs
=> grpc oneshot service

volo-build/src/grpc_backend.rs
=> remove mut for grpc method

Cargo.lock, examples/src/hello/thrift_client.rs, examples/src/hello/thrift_server.rs
=> chore(examples): thrift string default generated smolstr

Cargo.lock, examples/src/hello/grpc_client.rs, examples/src/hello/grpc_server.rs, volo-grpc/src/client/meta.rs, volo-grpc/src/metadata/mod.rs, volo/src/net/mod.rs
No need to write destination addr here.
=> fix(grpc): remove write destination addr

volo-thrift/src/codec/default/mod.rs
=> simplify mk_codec args
